In [3]:
def add_numbers(x, y, z=None):
    if(z == None):
        print('Flag is true')
        return x + y
        
    return x + y + z

print(add_numbers(3,4))
print(add_number(4,5,6))

Flag is true
7
15


In [4]:
# tuple

In [10]:
x = (1,3,4)
type(x)

tuple

In [9]:
y = [3,5,6, 'x']
type(y)

list

In [14]:
type('x')

NoneType

In [15]:
type(True)

bool

In [16]:
type(None)

NoneType

In [17]:
type(1.1)

float

In [18]:
type(1.22343232432432432432432)

float

In [23]:
x = [3 ,4 ,5 ,3 ,52,5 ]

In [21]:
for item in x:
    print(item)

3
4
5
3
52
5


In [29]:
i = 0
while( i != len(x)):
    print(x[i])
    i= i + 1

3
4
5
3
52
5


In [33]:
# Use '+' and '*' operator

In [37]:
y = x + x 
y

[3, 4, 5, 3, 52, 5, 3, 4, 5, 3, 52, 5]

In [46]:
z = x*3
z

[3, 4, 5, 3, 52, 5, 3, 4, 5, 3, 52, 5, 3, 4, 5, 3, 52, 5]

In [47]:
# in operatior


In [48]:
'a' in 'Sachin'

True

In [49]:
'ac' in 'sachin'

True

In [50]:
1 in x

False

In [51]:
3 in x

True

In [52]:
s = "Good Morning"

In [57]:
# substring from 3
s[3:]

'd Morning'

In [59]:
# last 3 letters
s[-3:]

'ing'

In [61]:
# letter starting from last 5 to last 2
s[-5: -2]

'rni'

In [64]:
fname = 'Sachin'
lname = 'Bhosale'
print(fname + ' ' + lname)
print(fname*3)
print('Sachin' in fname)

Sachin Bhosale
SachinSachinSachin
True


In [71]:
# split() funtion to split words or split('|') to split based on characters
name = "Sachin|E|Bhosale"
print(name.split('|'))

name = "Sachin E Bhosale"
print(name.split())

['Sachin', 'E', 'Bhosale']
['Sachin', 'E', 'Bhosale']


In [72]:
# concating other types to strings need conversion

'Sachin' + 1

TypeError: must be str, not int

In [73]:
'Sachin' + str(1)

'Sachin1'

In [92]:
dict1 = {'Sachin Bhosale' : 'sachinb4u@gmail.com', "Sourav Ganguly" : 'sourav@bcci.com', 'Virat Kohli' : 'virat@bcci.in'}
dict1

{'Sachin Bhosale': 'sachinb4u@gmail.com',
 'Sourav Ganguly': 'sourav@bcci.com',
 'Virat Kohli': 'virat@bcci.in'}

In [93]:
# check if key is present in dictionary
'Sachin Bhosale' in dict1

True

In [94]:
'Sachin' in dict1

False

In [95]:
dict1['MahendraSingh Dhoni'] = None
dict1

{'MahendraSingh Dhoni': None,
 'Sachin Bhosale': 'sachinb4u@gmail.com',
 'Sourav Ganguly': 'sourav@bcci.com',
 'Virat Kohli': 'virat@bcci.in'}

In [107]:
# iterate dictionary
for item in dict1.items():
    print(item)

print('---- Key values in variable -----')   
for key, value in dict1.items():
    print(key + ':' + str(value))

print('--------- print only values ------')
for val in dict1.values():
    print(val)

('Sachin Bhosale', 'sachinb4u@gmail.com')
('Sourav Ganguly', 'sourav@bcci.com')
('Virat Kohli', 'virat@bcci.in')
('MahendraSingh Dhoni', None)
---- Key values in variable -----
Sachin Bhosale:sachinb4u@gmail.com
Sourav Ganguly:sourav@bcci.com
Virat Kohli:virat@bcci.in
MahendraSingh Dhoni:None
--------- print only values ------
sachinb4u@gmail.com
sourav@bcci.com
virat@bcci.in
None


In [111]:
# Unpack tuple to different variables 
t = ("Sachin" , "Bhosale", 'sachinb4u@gmail.com', 'Pune')
fname, lname, email, location = t

In [113]:
print('fname=' + fname + ' lname='+ lname + ' email=' + email + ' location=' + location)

fname=Sachin lname=Bhosale email=sachinb4u@gmail.com location=Pune


In [114]:

# Python String Formatting 


In [120]:
sales_record = {
    'price' : 3.14,
    'num_items' : 12,
    'person' : 'Sachin'
}

sales_stmt= "{} bought {} item(s) at a price of {} each for a total of {}"

print(sales_stmt.format(
    sales_record['person'],
    sales_record['num_items'],
    sales_record['price'],
    sales_record['price'] * sales_record['num_items']
))

Sachin bought 12 item(s) at a price of 3.14 each for a total of 37.68


In [132]:
# print format using dictionary keys

sales_stmt= "{person} bought {num_items} item(s) at a price of {price} each for a total of {total} "


print(sales_stmt.format(**sales_record, total = sales_record['price'] * sales_record['num_items']))

# Note ** operator unpacks the keys to variables

sales_stmt= "{person:s} bought {num_items:d} item(s) at a price of {price:f} each for a total of {total:f} "

print(sales_stmt.format(**sales_record, total = sales_record['price'] * sales_record['num_items']))

Sachin bought 12 item(s) at a price of 3.14 each for a total of 37.68 
Sachin bought 12 item(s) at a price of 3.140000 each for a total of 37.680000 


In [134]:

# Expressing value with thousand separator

print("{:,}".format(1324234324324))

1,324,234,324,324


In [135]:


## Reading and writing CSV files
 


In [140]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:1]

[OrderedDict([('class', '3'),
              ('displ', 'NA'),
              ('trans', 'NA'),
              ('cyl', '4'),
              ('trans.dscr', 'A'),
              ('cty', '19.3'),
              ('hwy', '24.8'),
              ('fl', 'Unleaded Gasoline'),
              ('model', 'ALFETTA'),
              ('eng.dscr', 'NA'),
              ('eng.dscr.1', 'NA'),
              ('year', '1978'),
              ('manufacturer', 'ALFA ROMEO'),
              ('twodoor.p', '74'),
              ('twodoor.l', '7'),
              ('fourdoor.p', '89'),
              ('fourdoor.l', '9'),
              ('hatch.p', 'NA'),
              ('hatch.l', '          '),
              ('T', 'FALSE'),
              ('G', 'FALSE'),
              ('drv', 'NA'),
              ('vpc', 'NA'),
              ('bidx', 'NA'),
              ('x5c', 'NA'),
              ('S', 'FALSE'),
              ('eng.dscr.2', 'NA')])]

In [141]:
len(mpg)

36615

In [142]:
mpg[0].keys()

odict_keys(['class', 'displ', 'trans', 'cyl', 'trans.dscr', 'cty', 'hwy', 'fl', 'model', 'eng.dscr', 'eng.dscr.1', 'year', 'manufacturer', 'twodoor.p', 'twodoor.l', 'fourdoor.p', 'fourdoor.l', 'hatch.p', 'hatch.l', 'T', 'G', 'drv', 'vpc', 'bidx', 'x5c', 'S', 'eng.dscr.2'])

In [155]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'10', '12', '16', '2', '3', '4', '5', '6', '8'}

In [161]:
ctylist = list(str(d['cty']) for d in mpg)
len(ctylist)

36615

In [162]:

# Dates and Times in Python



In [163]:
import datetime as dt
import time as tm


In [165]:
# time returns the current time since epoch 1 Jan 1970
tm.time()

1516172720.99

In [168]:
# convert the timestamp to datetime

dtnow = dt.datetime.fromtimestamp(tm.time())

dtnow

datetime.datetime(2018, 1, 17, 12, 36, 24, 276485)

In [169]:
dtnow.year, dtnow.month, dtnow.day

(2018, 1, 17)

In [172]:
dtnow.hour, dtnow.minute, dtnow.second

(12, 36, 24)

In [180]:
delta = dt.timedelta(days=100)

In [178]:
today = dt.date.today()
today

datetime.date(2018, 1, 17)

In [182]:
today < today -delta

False

In [183]:

#  Python object oriented programming


In [212]:
class Employee:
    department = "Information Technlogy"
    
    # constructor
    def __init__(self, new_name="", new_location=""):
        self.name = new_name
        self.location = new_location
    
    # new method
    def set_name(self, new_name):
        self.name = new_name
        
    def set_location(self, new_location):
        self.location= new_location
        

In [213]:
emp = Employee()
emp.set_name('Sachin')
emp.set_location('Pune')

emp2 = Employee('Virat Kohli', 'Delhi')

In [214]:
print("{} lives in {} and works in department of {}".format(emp.name, emp.location, emp.department))


Sachin lives in Pune and works in department of Information Technlogy


In [216]:
print("{} lives in {} and works in department of {}".format(emp2.name, emp2.location, emp2.department))


Virat Kohli lives in Delhi and works in department of Information Technlogy


In [217]:
#
# Lambda and List Comprehensions
#

In [221]:
add_function = lambda a,b,c : a+b+c

In [222]:
add_function(1,4,5)

10

In [225]:
# iterate fomr 0 -999 and return even numbers
even_num = []

for num in range (0,1000):
    if( num %2 == 0):
        even_num.append(num)
        
print(even_num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [229]:
even_num = [n for n in range (0,1000) if n%2 == 0]

print(even_num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [230]:

# Numerical python (NumPy) library


In [232]:
import numpy as np

In [243]:
mylist = [1,3,4,5,5]

In [244]:
x = np.array(mylist)
x

array([1, 3, 4, 5, 5])

In [245]:
x1 = np.array([4,6,78,88])
x1

array([ 4,  6, 78, 88])

## Multi dimensional array



In [254]:
ar1 = np.array([[2,455,67], [4,7,8]])
ar1

array([[  2, 455,  67],
       [  4,   7,   8]])

In [255]:
ar1.shape

(2, 3)

In [400]:
a = lambda a : a + 1

In [401]:
type(a)

function

In [405]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [413]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])