In [3]:
import pandas as pd
import numpy as np

## pandas `cut` function for scalar value

In [13]:
x = np.random.randint(10, 100, 5)
x

array([62, 53, 11, 40, 15])

In [14]:
pd.cut(x,5)

[(51.8, 62.0], (51.8, 62.0], (10.949, 21.2], (31.4, 41.6], (10.949, 21.2]]
Categories (5, interval[float64]): [(10.949, 21.2] < (21.2, 31.4] < (31.4, 41.6] < (41.6, 51.8] < (51.8, 62.0]]

In [15]:
pd.cut(x,5,labels=['a', 'b', 'c', 'd', 'e'])

[e, e, a, c, a]
Categories (5, object): [a < b < c < d < e]

## Creating DataFrame

In [22]:
d = {
    'col1' : [1,3,4,5,5],
    'col2' : [2,5,6,2,6]
}

pd.DataFrame(d, index = list('abcde'))

col1  col2
a     1     2
b     3     5
c     4     6
d     5     2
e     5     6

In [30]:
df = (pd.DataFrame(
    data=np.random.randint(low=0, high=100, size=(5,5)), 
    index=list('abcde'), 
    columns=['one', 'two', 'three', 'four', 'five']))
df

one  two  three  four  five
a   12   46     13     2     5
b   83   23      2    10    42
c   67   76     70    23    67
d   41   89     83     1    12
e   39   72     46    31     7

In [35]:
df.iloc[0]

one      12
two      46
three    13
four      2
five      5
Name: a, dtype: int32

In [40]:
df.loc['b']

one      83
two      23
three     2
four     10
five     42
Name: b, dtype: int32

In [42]:
df['two']

a    46
b    23
c    76
d    89
e    72
Name: two, dtype: int32

In [43]:
type(df['three'])

pandas.core.series.Series

In [45]:
type(df.iloc[1])

pandas.core.series.Series

In [46]:
df.shape

(5, 5)

In [47]:
df.size

25

In [48]:
df.values

array([[12, 46, 13,  2,  5],
       [83, 23,  2, 10, 42],
       [67, 76, 70, 23, 67],
       [41, 89, 83,  1, 12],
       [39, 72, 46, 31,  7]])

In [49]:
type(df.values)

numpy.ndarray

## DataFram `aggregate`

In [54]:
df.agg(np.average, axis=0)

   one  two  three  four  five
a   12   46     13     2     5
b   83   23      2    10    42
c   67   76     70    23    67
d   41   89     83     1    12
e   39   72     46    31     7
one      242
two      306
three    214
four      67
five     133
dtype: int64
one      48.4
two      61.2
three    42.8
four     13.4
five     26.6
dtype: float64


In [56]:
df.aggregate(['min', 'max'])

one  two  three  four  five
min   12   23      2     1     5
max   83   89     83    31    67

In [58]:
df.aggregate(['min', 'max'])

one  two  three  four  five
min   12   23      2     1     5
max   83   89     83    31    67

In [65]:
df.agg({ 'two' : ['average', 'std'], 'one' : ['average', 'min']})

two   one
average  61.200000  48.4
min            NaN  12.0
std      26.451843   NaN

In [68]:
df

one  two  three  four  five
a   12   46     13     2     5
b   83   23      2    10    42
c   67   76     70    23    67
d   41   89     83     1    12
e   39   72     46    31     7

## DataFram `apply`

In [69]:
df.apply(lambda x : np.mean(x))

one      48.4
two      61.2
three    42.8
four     13.4
five     26.6
dtype: float64

In [70]:
df.applymap(lambda x : '%.2f' % x)

one    two  three   four   five
a  12.00  46.00  13.00   2.00   5.00
b  83.00  23.00   2.00  10.00  42.00
c  67.00  76.00  70.00  23.00  67.00
d  41.00  89.00  83.00   1.00  12.00
e  39.00  72.00  46.00  31.00   7.00

In [73]:
df.get_values()

array([[12, 46, 13,  2,  5],
       [83, 23,  2, 10, 42],
       [67, 76, 70, 23, 67],
       [41, 89, 83,  1, 12],
       [39, 72, 46, 31,  7]])

In [77]:
df

one  two  three  four  five
a   12   46     13     2     5
b   83   23      2    10    42
c   67   76     70    23    67
d   41   89     83     1    12
e   39   72     46    31     7

# DataFrame `groupby`

In [197]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)

df

Points  Rank    Team  Year
0      876     1  Riders  2014
1      789     2  Riders  2015
2      863     2  Devils  2014
3      673     3  Devils  2015
4      741     3   Kings  2014
5      812     4   kings  2015
6      756     1   Kings  2016
7      788     1   Kings  2017
8      694     2  Riders  2016
9      701     4  Royals  2014
10     804     1  Royals  2015
11     690     2  Riders  2017

In [154]:
df.groupby('Year').groups

{2014: Int64Index([0, 2, 4, 9], dtype='int64'),
 2015: Int64Index([1, 3, 5, 10], dtype='int64'),
 2016: Int64Index([6, 8], dtype='int64'),
 2017: Int64Index([7, 11], dtype='int64')}

In [155]:
df_grouped = df.groupby('Year')

for name, group in df_grouped:
    print(name)
    print(group)

2014
   Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014
2015
    Points  Rank    Team  Year
1      789     2  Riders  2015
3      673     3  Devils  2015
5      812     4   kings  2015
10     804     1  Royals  2015
2016
   Points  Rank    Team  Year
6     756     1   Kings  2016
8     694     2  Riders  2016
2017
    Points  Rank    Team  Year
7      788     1   Kings  2017
11     690     2  Riders  2017


In [156]:
print(df_grouped.get_group(2014))

   Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014


In [162]:
# grouping by function
df.reset_index()
df = df.set_index('Team')

# index passed to function
def fun(item):
    return item[0]

for name, group in df.groupby(fun):
    print('There are {} records in {} group'.format(str(len(group)), name))


There are 2 records in D group
There are 3 records in K group
There are 6 records in R group
There are 1 records in k group


In [163]:
df.groupby('Year').count()

Points  Rank
Year              
2014       4     4
2015       4     4
2016       2     2
2017       2     2

### DataFrame `aggregate`

In [216]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Points  Rank    Team  Year
0      876     1  Riders  2014
1      789     2  Riders  2015
2      863     2  Devils  2014
3      673     3  Devils  2015
4      741     3   Kings  2014
5      812     4   kings  2015
6      756     1   Kings  2016
7      788     1   Kings  2017
8      694     2  Riders  2016
9      701     4  Royals  2014
10     804     1  Royals  2015
11     690     2  Riders  2017

In [217]:
# Find out how many teams played year wise

#df.set_index(['Year', 'Team'])
def func(row):
    return len(row)

df.groupby('Year').agg(func)['Team']

Year
2014    4
2015    4
2016    2
2017    2
Name: Team, dtype: int64

In [218]:
# return the teams which have participated 3 or more times in IPL

df.groupby('Team').filter(lambda x : len(x) >= 3)

Points  Rank    Team  Year
0      876     1  Riders  2014
1      789     2  Riders  2015
4      741     3   Kings  2014
6      756     1   Kings  2016
7      788     1   Kings  2017
8      694     2  Riders  2016
11     690     2  Riders  2017

In [220]:
df.groupby(level=0)['Year', 'Team']
#df

In [222]:
(df.set_index('Year')
     .groupby(level=0)['Points']
     .agg({'avg' : np.average, 'min' : np.min, 'max': np.max})

)

c:\softwares\python\python36-32\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  This is separate from the ipykernel package so we can avoid doing imports until


avg  min  max
Year                  
2014  795.25  701  876
2015  769.50  673  812
2016  725.00  694  756
2017  739.00  690  788

## `Pivot Table`

In [116]:
# show the year wise ranking for the teams

df = pd.DataFrame(ipl_data)
pd.pivot_table(df, index=['Year'], values='Rank',columns='Team' , fill_value="-")

Team Devils Kings  Riders Royals kings
Year                                  
2014      2     3     1.0      4     -
2015      3     -     2.0      1     4
2016      -     1     2.0      -     -
2017      -     1     2.0      -     -

## DataFram `merge`

In [118]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [119]:
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [120]:
pd.merge(left, right, on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [121]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                   'key2': ['K0', 'K1', 'K0', 'K1'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [122]:
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                  'key2': ['K0', 'K0', 'K0', 'K0'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [124]:
pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [129]:
df = pd.merge(left, right, on=['key1', 'key2'],how='outer')
df.fillna('-')

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A1  B1   K0   K1   -   -
2  A2  B2   K1   K0  C1  D1
3  A2  B2   K1   K0  C2  D2
4  A3  B3   K2   K1   -   -
5   -   -   K2   K0  C3  D3

In [130]:
left = pd.DataFrame({'A' : [1,2], 'B' : [2, 2]})
left

A  B
0  1  2
1  2  2

In [131]:
right = pd.DataFrame({'A' : [4,5,6], 'B': [2,2,2]})
right

A  B
0  4  2
1  5  2
2  6  2

In [135]:
# when column in mismatching, left and right values are preserved with columns with prefix 

pd.merge(left, right, on='B', how='inner')


A_x  B  A_y
0    1  2    4
1    1  2    5
2    1  2    6
3    2  2    4
4    2  2    5
5    2  2    6

In [137]:
pd.merge(left, right, on='B', how='inner', validate='one_to_one')

MergeError: Merge keys are not unique in either left or right dataset; not a one-to-one merge

In [139]:
pd.merge(left, right, on='B', how='outer', indicator=True)

A_x  B  A_y _merge
0    1  2    4   both
1    1  2    5   both
2    1  2    6   both
3    2  2    4   both
4    2  2    5   both
5    2  2    6   both

## Scales

In [228]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Points  Rank    Team  Year
0      876     1  Riders  2014
1      789     2  Riders  2015
2      863     2  Devils  2014
3      673     3  Devils  2015
4      741     3   Kings  2014
5      812     4   kings  2015
6      756     1   Kings  2016
7      788     1   Kings  2017
8      694     2  Riders  2016
9      701     4  Royals  2014
10     804     1  Royals  2015
11     690     2  Riders  2017

In [233]:
# df['Points'].astype('category',
#                    categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'],
#                              ordered=True)